FROM openjdk:17

ARG DB_URL
ARG DB_USERNAME
ARG DB_PASSWORD
ARG PROFILE
ARG HOSTNAME
ARG EUREKA_URL

ENV DB_URL=${DB_URL}
ENV DB_USERNAME=${DB_USERNAME}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV PROFILE=${PROFILE}
ENV HOSTNAME=${HOSTNAME}
ENV EUREKA_URL=${EUREKA_URL}

COPY build/libs/*.jar app.jar

CMD ["java", "-jar", "app.jar"]