FROM openjdk:17

ARG DB_URL
ARG DB_USERNAME
ARG DB_PASSWORD
ARG PROFILE

ENV DB_URL=${DB_URL}
ENV DB_USERNAME=${DB_USERNAME}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV PROFILE=${PROFILE}

COPY build/libs/*.jar app.jar

CMD ["java", "-jar", "app.jar"]