spring:
  application:
    name: posting-service

  jpa:
    properties:
      hibernate:
        default_schema: public

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

  instance:
    hostname: ${HOSTNAME}

file:
  base-url: ${HOSTNAME}