server:
  port: ${PORT}

spring:
  profiles:
    active: ${PROFILE}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        default_batch_fetch_size: 1000
        format_sql: true
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  cache:
    jcache:
      config: classpath:ehcache.xml

springdoc:
  swagger-ui:
    path: /api/posting/swagger-ui
  api-docs:
    path: /api/posting/swagger-ui/api-docs

swagger:
  server: ${GATEWAY_URL}

api:
  url: ${GATEWAY_URL}

file:
  base-url: ${FILE_SERVER}
  save-path: /home/upload/