spring:
  application:
    name: posting-service-dev

  jpa:
    properties:
      hibernate:
        default_schema: dev

eureka:
  client:
    service-url:
      defaultZone: http://52.79.158.1:8761/eureka/

  instance:
    hostname: ${HOSTNAME}