spring:
  application:
    name: posting-service-local

  jpa:
    properties:
      hibernate:
        default_schema: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/