server:
  port: 8010

spring:
  profiles:
    active: pd

  application:
    name: posting-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://52.78.12.178:8761/eureka/
