spring:
  application:
    name: posting-service-dev

  jpa:
    properties:
      hibernate:
        default_schema: dev
        ddl-auto: create

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost