spring:
  application:
    name: posting-service-dev

  jpa:
    properties:
      hibernate:
        default_schema: dev
        hbm2ddl.auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost

swagger:
  server: http://localhost:8000

file:
  base-url: http://localhost