spring:
  application:
    name: posting-service-dev

  jpa:
    properties:
      hibernate:
        default_schema: dev

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

  instance:
    hostname: ${HOSTNAME}